apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: emitter
  name: emitter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: emitter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: emitter
    spec:
      containers:
      - args:
        - python
        - /opt/project/data/emitter.py
        image: emitter
        imagePullPolicy: ""
        name: emitter
        resources: {}
        volumeMounts:
        - mountPath: /opt/project
          name: emitter-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: emitter-claim0
        persistentVolumeClaim:
          claimName: emitter-claim0
status: {}
