apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hazelcast-mancenter
  name: hazelcast-mancenter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hazelcast-mancenter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: hazelcast-mancenter
    spec:
      containers:
      - image: hazelcast-mancenter
        imagePullPolicy: ""
        name: hazelcast-mancenter
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /opt/project
          name: hazelcast-mancenter-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: hazelcast-mancenter-claim0
        persistentVolumeClaim:
          claimName: hazelcast-mancenter-claim0
status: {}
