apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mapserver
  name: mapserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mapserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: mapserver
    spec:
      containers:
      - args:
        - bokeh
        - serve
        - /opt/project/data/beijing.py
        env:
        - name: GOOGLE_MAPS_API_KEY
        image: mapserver
        imagePullPolicy: ""
        name: mapserver
        ports:
        - containerPort: 5006
        resources: {}
        volumeMounts:
        - mountPath: /opt/project
          name: mapserver-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mapserver-claim0
        persistentVolumeClaim:
          claimName: mapserver-claim0
status: {}
